# Generated by Django 4.0.1 on 2022-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
